### ISSUE TITLE
Inconsistent commit messages

### ISSUE THREAD

**Issue by lucymonie** [FAC-11/week1-dyrt#91]
Ideally your commit messages should be start with a verb like 'Adds', 'Updates', 'Fixes' or 'Removes'. Some teams decide to use the past tense instead ('Added', Updated', 'Fixed' etc). The message should finish a sentence that starts 'This commit...'

It's good to decide on a style and all use it in every commit message so your commit history tells the story of what happened.

'Adds contact details for team members'
'Updates stylesin About us section'
'Removes a broken image link'

**Comment by dangerdak** [comment]
Noted :)
